apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: "adifw1ce5z4sga"
      access: proxy
      url: http://prometheus-service.monitoring.svc.cluster.local:9090
