apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistent-storage
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi