apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  cpu-usage.rules: |-
    groups:
      - name: cpu-usage
        rules:
          - alert: HighCpuUsage
            expr: avg by (instance) (rate(node_cpu_seconds_total{mode!~"idle|iowait|steal"}[1m])) * 100 > 40
            for: 1m
            labels:
              severity: "warning"
            annotations:
              summary: "Utilisation élevée du CPU détectée"
              description: "L'utilisation du CPU est supérieure à 40% en moyenne sur toutes les instances pendant la dernière minute"
  memory-usage.rules: |-
    groups:
      - name: memory-usage
        rules:
          - alert: HighMemoryUsage
            expr: (sum by (instance) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum by (instance) (node_memory_MemTotal_bytes)) * 100 > 50
            for: 1m
            labels:
              severity: "warning"
            annotations:
              summary: "Utilisation élevée de la mémoire détectée"
              description: "L'utilisation de la mémoire est supérieure à 50% en moyenne sur toutes les instances pendant la dernière minute"
  pod-failure.rules: |-
    groups:
      - name: pod-failure
        rules:
          - alert: HighPodFailure
            expr: count(kube_pod_status_phase{phase="Failed"}) > 5
            for: 1m
            labels:
              severity: "critical"
            annotations:
              summary: "Nombre élevé de pods en échec détecté"
              description: "Plus de 5 pods sont dans l'état 'Failed', indiquant des problèmes potentiels avec les déploiements ou l'exécution des applications depuis plus d'1 minute"
