apiVersion: v1
kind: Service
metadata:
  name: web-client-service
spec:
  selector:
    app: web-client
    tier: laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
