apiVersion: batch/v1
kind: Job
metadata:
  name: web-client-migration-job-20240421t203314z

spec:
  template:
    spec:
      containers:
        - name: web-client-migration
          image: pokesrater/t-nsa-800:1.13.0
          envFrom:
            - configMapRef:
                name: web-client
            - secretRef:
                name: web-client
          command: ["php", "artisan", "migrate", "--force"]
      restartPolicy: Never
