apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  default.tmpl: |
    {"content": "{{ range .Alerts }}Alert: {{ .Labels.alertname }} - {{ if .Annotations.description }}{{ .Annotations.description }}{{ else }}No description provided.{{ end }}{{ end }}"}
