apiVersion: v1
kind: Secret
data:
  URL_DISCORD: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTIyNDY1NzIxODIwNTY0NjkyOC9HcUZkcFl6N3MzWmFyQjIzLVRYV3hCdU1KRFlrS3hqOXVfXzBrRmI4cS1FYTJreWRlSkV0SDJpbEdxUmFmbzZ1UXNwSw==
metadata:
  name: alertmanager-secret
  namespace: monitoring
type: Opaque
